<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-G07M1S2" failures="2" tests="22" name="interviewQue.ReRunTest" time="0.115" errors="0" timestamp="2024-10-03T00:15:26 IST" skipped="18">
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.004">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleOne" time="0.004"/>
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.023">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.005">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.003">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.007">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.004">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.006">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.003">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.006">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.008">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.003">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.007">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.004">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.003">
    <failure message="failed intensionally" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed intensionally
at org.testng.Assert.fail(Assert.java:110)
at interviewQue.ReRunTest.sampleFour(ReRunTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.008">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleFour" time="0.004">
    <skipped/>
  </testcase> <!-- sampleFour -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleThree" time="0.005"/>
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.002">
    <failure message="failed intensionally" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed intensionally
at org.testng.Assert.fail(Assert.java:110)
at interviewQue.ReRunTest.sampleTwo(ReRunTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sampleTwo -->
  <system-out/>
  <testcase classname="interviewQue.ReRunTest" name="sampleTwo" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <system-out/>
</testsuite> <!-- interviewQue.ReRunTest -->
